import ffmpeg from 'fluent-ffmpeg';
import { createWriteStream, promises as fs } from 'fs';
import path from 'path';
import { spawn } from 'child_process';
import type { FFmpegConfig, RenderProgress } from './types';

/**
 * Options for FFmpeg encoding
 */
export interface EncodeOptions {
  /** Input frame directory or pattern */
  inputPattern: string;
  /** Output file path */
  outputPath: string;
  /** Frame rate */
  fps: number;
  /** Width */
  width: number;
  /** Height */
  height: number;
  /** Video codec */
  codec?: 'libx264' | 'libx265' | 'libvpx' | 'libvpx-vp9' | 'libaom-av1' | 'prores';
  /** Quality CRF (0-51) */
  quality?: number;
  /** Pixel format */
  pixelFormat?: string;
  /** Audio file to include */
  audioFile?: string;
  /** Audio codec */
  audioCodec?: 'aac' | 'mp3' | 'opus' | 'none';
  /** Audio bitrate */
  audioBitrate?: string;
  /** Progress callback */
  onProgress?: (progress: RenderProgress) => void;
  /** Start time for progress calculation */
  startTime?: number;
  /** Total frames for progress calculation */
  totalFrames?: number;
}

/**
 * Options for creating GIF
 */
export interface GifOptions {
  /** Input frame directory or pattern */
  inputPattern: string;
  /** Output file path */
  outputPath: string;
  /** Frame rate */
  fps: number;
  /** Width (optional, for scaling) */
  width?: number;
  /** Height (optional, for scaling) */
  height?: number;
  /** Number of colors (2-256, default: 256) */
  colors?: number;
  /** Dithering algorithm */
  dither?: 'none' | 'floyd_steinberg' | 'bayer';
}

/**
 * FFmpeg encoder class
 */
export class FFmpegEncoder {
  private config: FFmpegConfig;

  constructor(config: FFmpegConfig = {}) {
    this.config = config;

    // Set custom paths if provided
    if (config.ffmpegPath) {
      ffmpeg.setFfmpegPath(config.ffmpegPath);
    }
    if (config.ffprobePath) {
      ffmpeg.setFfprobePath(config.ffprobePath);
    }
  }

  /**
   * Encode frames to video
   */
  async encodeToVideo(options: EncodeOptions): Promise<void> {
    const {
      inputPattern,
      outputPath,
      fps,
      width,
      height,
      codec = 'libx264',
      quality = 23,
      pixelFormat = 'yuv420p',
      audioFile,
      audioCodec = 'aac',
      audioBitrate = '128k',
      onProgress,
      startTime = Date.now(),
      totalFrames = 0,
    } = options;

    return new Promise((resolve, reject) => {
      let command = ffmpeg()
        .input(inputPattern)
        .inputFPS(fps)
        .videoCodec(codec);

      // Configure codec-specific options
      const outputOptions: string[] = [];

      if (codec === 'libaom-av1') {
        // AV1 specific options
        outputOptions.push(
          `-crf ${quality}`,
          `-b:v 0`, // Use constant quality mode
          `-cpu-used 4`, // Encoding speed (0-8, higher is faster)
          `-row-mt 1`, // Enable row-based multithreading
          `-pix_fmt ${pixelFormat}`
        );
      } else {
        // Default options for other codecs
        outputOptions.push(
          `-crf ${quality}`,
          `-pix_fmt ${pixelFormat}`,
          `-preset medium`
        );
      }

      command = command
        .outputOptions(outputOptions)
        .size(`${width}x${height}`);

      // Add metadata
      command = command
        .outputOptions([
          '-metadata', 'title=Generated by Rendervid',
          '-metadata', 'artist=Rendervid by FlowHunt.io',
          '-metadata', 'comment=Created with Rendervid - https://flowhunt.io',
          '-metadata', 'encoder=Rendervid',
        ]);

      // Add audio if provided
      if (audioFile && audioCodec !== 'none') {
        command = command
          .input(audioFile)
          .audioCodec(audioCodec)
          .audioBitrate(audioBitrate);
      }

      command
        .output(outputPath)
        .on('progress', (progress) => {
          if (onProgress && totalFrames > 0) {
            const elapsed = (Date.now() - startTime) / 1000;
            const currentFrame = progress.frames || 0;
            const percent = (currentFrame / totalFrames) * 100;
            const fps = progress.currentFps || currentFrame / elapsed;
            const remainingFrames = totalFrames - currentFrame;
            const eta = fps > 0 ? remainingFrames / fps : undefined;

            onProgress({
              phase: 'encoding',
              currentFrame,
              totalFrames,
              percent: Math.min(100, percent),
              eta,
              elapsed,
              fps,
            });
          }
        })
        .on('error', (err) => {
          reject(new Error(`FFmpeg error: ${err.message}`));
        })
        .on('end', () => {
          resolve();
        })
        .run();
    });
  }

  /**
   * Encode frames to video using streaming (pipe frames directly to FFmpeg stdin)
   */
  async encodeToVideoStream(
    frameIterator: AsyncIterableIterator<Buffer>,
    options: Omit<EncodeOptions, 'inputPattern'>
  ): Promise<void> {
    const {
      outputPath,
      fps,
      width,
      height,
      codec = 'libx264',
      quality = 23,
      pixelFormat = 'yuv420p',
      audioFile,
      audioCodec = 'aac',
      audioBitrate = '128k',
      onProgress,
      startTime = Date.now(),
      totalFrames = 0,
    } = options;

    return new Promise((resolve, reject) => {
      // Build FFmpeg command arguments
      const args: string[] = [
        '-f', 'image2pipe',
        '-c:v', 'png',
        '-r', fps.toString(),
        '-i', 'pipe:0', // Read from stdin
      ];

      // Add audio if provided
      if (audioFile && audioCodec !== 'none') {
        args.push('-i', audioFile);
        args.push('-c:a', audioCodec);
        args.push('-b:a', audioBitrate);
      }

      // Add video codec and options
      args.push('-c:v', codec);

      // Codec-specific options
      if (codec === 'libaom-av1') {
        args.push(
          '-crf', quality.toString(),
          '-b:v', '0',
          '-cpu-used', '4',
          '-row-mt', '1',
          '-pix_fmt', pixelFormat
        );
      } else {
        args.push(
          '-crf', quality.toString(),
          '-pix_fmt', pixelFormat,
          '-preset', 'medium'
        );
      }

      // Add metadata
      args.push(
        '-metadata', 'title=Generated by Rendervid',
        '-metadata', 'artist=Rendervid by FlowHunt.io',
        '-metadata', 'comment=Created with Rendervid - https://flowhunt.io',
        '-metadata', 'encoder=Rendervid'
      );

      args.push(
        '-s', `${width}x${height}`,
        '-y', // Overwrite output file
        outputPath
      );

      // Spawn FFmpeg process
      const ffmpegPath = this.config.ffmpegPath || 'ffmpeg';
      const process = spawn(ffmpegPath, args);

      let currentFrame = 0;
      let encoding = true;

      // Handle stderr for progress reporting
      process.stderr.on('data', (data: Buffer) => {
        const output = data.toString();

        // Parse frame number from FFmpeg output
        const frameMatch = output.match(/frame=\s*(\d+)/);
        if (frameMatch && onProgress && totalFrames > 0) {
          currentFrame = parseInt(frameMatch[1], 10);
          const elapsed = (Date.now() - startTime) / 1000;
          const percent = (currentFrame / totalFrames) * 100;
          const fps = currentFrame / elapsed;
          const remainingFrames = totalFrames - currentFrame;
          const eta = fps > 0 ? remainingFrames / fps : undefined;

          onProgress({
            phase: 'encoding',
            currentFrame,
            totalFrames,
            percent: Math.min(100, percent),
            eta,
            elapsed,
            fps,
          });
        }
      });

      // Handle process errors
      process.on('error', (err) => {
        encoding = false;
        reject(new Error(`FFmpeg process error: ${err.message}`));
      });

      process.on('exit', (code) => {
        encoding = false;
        if (code === 0) {
          resolve();
        } else {
          reject(new Error(`FFmpeg exited with code ${code}`));
        }
      });

      // Pipe frames to FFmpeg stdin
      (async () => {
        try {
          for await (const frameBuffer of frameIterator) {
            if (!encoding) break;

            // Write frame to stdin
            const written = process.stdin.write(frameBuffer);

            // If buffer is full, wait for drain event
            if (!written) {
              await new Promise<void>((resolve) => {
                process.stdin.once('drain', resolve);
              });
            }
          }

          // Close stdin to signal end of input
          process.stdin.end();
        } catch (err) {
          reject(err);
          process.kill();
        }
      })();
    });
  }

  /**
   * Encode frames to GIF
   */
  async encodeToGif(options: GifOptions): Promise<void> {
    const {
      inputPattern,
      outputPath,
      fps,
      width,
      height,
      colors = 256,
      dither = 'floyd_steinberg',
    } = options;

    // Create a palette first for better quality
    const tempDir = path.dirname(outputPath);
    const palettePath = path.join(tempDir, 'palette.png');

    // Generate palette
    await new Promise<void>((resolve, reject) => {
      let filterStr = `fps=${fps}`;
      if (width || height) {
        filterStr += `,scale=${width || -1}:${height || -1}:flags=lanczos`;
      }
      filterStr += `,palettegen=max_colors=${colors}`;

      ffmpeg()
        .input(inputPattern)
        .inputFPS(fps)
        .complexFilter(filterStr)
        .output(palettePath)
        .on('error', reject)
        .on('end', () => resolve())
        .run();
    });

    // Generate GIF using palette
    await new Promise<void>((resolve, reject) => {
      let filterStr = `fps=${fps}`;
      if (width || height) {
        filterStr += `,scale=${width || -1}:${height || -1}:flags=lanczos`;
      }

      const ditherStr = dither === 'none' ? '' : `:dither=${dither}`;
      const paletteFilter = `[0:v][1:v]paletteuse${ditherStr}`;

      ffmpeg()
        .input(inputPattern)
        .inputFPS(fps)
        .input(palettePath)
        .complexFilter([filterStr, paletteFilter].join(';'))
        .output(outputPath)
        .on('error', reject)
        .on('end', () => resolve())
        .run();
    });

    // Clean up palette file
    await fs.unlink(palettePath).catch(() => {});
  }

  /**
   * Get video duration using FFprobe
   */
  async getVideoDuration(filePath: string): Promise<number> {
    return new Promise((resolve, reject) => {
      ffmpeg.ffprobe(filePath, (err, metadata) => {
        if (err) {
          reject(err);
        } else {
          resolve(metadata.format.duration || 0);
        }
      });
    });
  }

  /**
   * Get file size
   */
  async getFileSize(filePath: string): Promise<number> {
    const stats = await fs.stat(filePath);
    return stats.size;
  }

  /**
   * Add metadata to an image file
   */
  async addImageMetadata(filePath: string): Promise<void> {
    return new Promise((resolve, reject) => {
      const tempPath = `${filePath}.tmp`;

      ffmpeg(filePath)
        .outputOptions([
          '-metadata', 'title=Generated by Rendervid',
          '-metadata', 'artist=Rendervid by FlowHunt.io',
          '-metadata', 'comment=Created with Rendervid - https://flowhunt.io',
          '-metadata', 'Software=Rendervid',
        ])
        .output(tempPath)
        .on('error', (err) => {
          reject(new Error(`Failed to add metadata: ${err.message}`));
        })
        .on('end', async () => {
          try {
            // Replace original with metadata version
            await fs.unlink(filePath);
            await fs.rename(tempPath, filePath);
            resolve();
          } catch (err) {
            reject(err);
          }
        })
        .run();
    });
  }

  /**
   * Check if FFmpeg is available
   */
  async checkFFmpeg(): Promise<boolean> {
    return new Promise((resolve) => {
      ffmpeg.getAvailableFormats((err) => {
        resolve(!err);
      });
    });
  }
}

/**
 * Create an FFmpeg encoder
 */
export function createFFmpegEncoder(config: FFmpegConfig = {}): FFmpegEncoder {
  return new FFmpegEncoder(config);
}
